import os

# 定义 free_ebook_maker 的核心内容模板
content_templates = {
    1: {
        "feature1": "One-click PDF to EPUB conversion",
        "feature1_desc": "Convert existing PDF documents to EPUB format with a single click, preserving layout and formatting for optimal e-reader compatibility.",
        "feature2": "Batch processing support",
        "feature2_desc": "Process multiple files simultaneously, saving time when converting large collections of documents to ebook formats.",
        "feature3": "Metadata editor",
        "feature3_desc": "Easily edit ebook metadata including title, author, publisher, and ISBN to ensure proper cataloging across devices.",
        "step1": "Import PDF files",
        "step1_desc": "Upload your PDF documents to the free_ebook_maker dashboard, either by dragging and dropping or selecting from your file system.",
        "step2": "Configure conversion settings",
        "step2_desc": "Select output format (EPUB), adjust layout preferences, and set metadata fields for your ebook.",
        "step3": "Start conversion",
        "step3_desc": "Click the 'Convert' button to begin the process, and download the converted EPUB file once complete.",
        "practice1": "Optimize PDF quality before conversion",
        "practice1_desc": "Ensure your source PDF has clear text and proper formatting to achieve the best results in the EPUB output.",
        "practice2": "Test on multiple devices",
        "practice2_desc": "Verify your converted ebook displays correctly across different e-readers and reading apps to ensure compatibility.",
        "focus": "PDF to EPUB conversion efficiency and quality"
    },
    2: {
        "feature1": "Professional cover design tool",
        "feature1_desc": "Create stunning ebook covers with drag-and-drop functionality, customizable templates, and high-resolution graphics support.",
        "feature2": "Typography controls",
        "feature2_desc": "Fine-tune font styles, sizes, and spacing to create visually appealing text layouts that enhance readability.",
        "feature3": "Color scheme generator",
        "feature3_desc": "Generate professional color palettes that complement your ebook content and brand identity.",
        "step1": "Select cover template",
        "step1_desc": "Choose from a library of professionally designed cover templates or start with a blank canvas.",
        "step2": "Customize design elements",
        "step2_desc": "Add text, images, and graphics, adjusting layout and styling to match your ebook's theme.",
        "step3": "Export cover",
        "step3_desc": "Download your cover in high-resolution format optimized for ebook platforms.",
        "practice1": "Use high-quality images",
        "practice1_desc": "Incorporate high-resolution images and graphics to ensure your cover looks professional across all devices.",
        "practice2": "Test cover dimensions",
        "practice2_desc": "Verify your cover meets the size requirements of major ebook platforms like Amazon Kindle and Apple Books.",
        "focus": "Cover design and typography for professional ebooks"
    },
    3: {
        "feature1": "Multi-format export",
        "feature1_desc": "Export your ebook in multiple formats including EPUB, MOBI, PDF, and AZW3 to reach readers across all devices.",
        "feature2": "Format compatibility checker",
        "feature2_desc": "Automatically detect and resolve formatting issues that might cause problems on specific e-reader devices.",
        "feature3": "Cross-platform preview",
        "feature3_desc": "Preview your ebook as it will appear on different devices and platforms before publishing.",
        "step1": "Create or import content",
        "step1_desc": "Write your ebook directly in the editor or import existing content from Word, Google Docs, or other formats.",
        "step2": "Format and style content",
        "step2_desc": "Apply consistent styling, add images, and organize content into chapters and sections.",
        "step3": "Export in multiple formats",
        "step3_desc": "Select the desired output formats and generate optimized files for each platform.",
        "practice1": "Test on target devices",
        "practice1_desc": "Always test your exported ebook on the specific devices and platforms you intend to support.",
        "practice2": "Optimize file size",
        "practice2_desc": "Balance image quality with file size to ensure fast downloads and smooth reading experiences.",
        "focus": "Multi-format compatibility and cross-platform optimization"
    },
    4: {
        "feature1": "Interactive table of contents",
        "feature1_desc": "Generate automatic, clickable tables of contents that make navigation easy for readers.",
        "feature2": "Chapter organization tools",
        "feature2_desc": "Easily create, rearrange, and manage chapters and sections with drag-and-drop functionality.",
        "feature3": "Hyperlink management",
        "feature3_desc": "Add and manage internal and external links to enhance navigation and reader experience.",
        "step1": "Create chapter structure",
        "step1_desc": "Outline your ebook by creating chapters and sections in the desired order.",
        "step2": "Add content to chapters",
        "step2_desc": "Fill each chapter with your content, ensuring proper formatting and styling.",
        "step3": "Generate table of contents",
        "step3_desc": "Automatically generate a clickable table of contents based on your chapter structure.",
        "practice1": "Keep chapters concise",
        "practice1_desc": "Break content into manageable chapters to improve readability and navigation.",
        "practice2": "Use consistent headings",
        "practice2_desc": "Apply consistent heading styles throughout your ebook for a professional appearance.",
        "focus": "Content organization and navigation optimization"
    },
    5: {
        "feature1": "Image optimization tools",
        "feature1_desc": "Automatically optimize images for ebook formats, reducing file size without sacrificing quality.",
        "feature2": "Image placement and alignment",
        "feature2_desc": "Precisely position and align images within your content for professional layout.",
        "feature3": "Caption and alt text support",
        "feature3_desc": "Add captions and alt text to images for accessibility and improved reader experience.",
        "step1": "Import images",
        "step1_desc": "Upload images to your ebook project, supporting multiple file formats including JPG, PNG, and SVG.",
        "step2": "Optimize and position images",
        "step2_desc": "Resize, crop, and position images within your content, adding captions if needed.",
        "step3": "Preview and adjust",
        "step3_desc": "Preview how images appear in the final ebook and make adjustments as needed.",
        "practice1": "Use appropriate image formats",
        "practice1_desc": "Choose the right image format (JPG for photos, PNG for graphics with transparency) for optimal results.",
        "practice2": "Compress images appropriately",
        "practice2_desc": "Balance image quality with file size to ensure your ebook remains manageable.",
        "focus": "Image optimization and layout for ebooks"
    },
    6: {
        "feature1": "Collaborative editing",
        "feature1_desc": "Invite team members to collaborate on ebook projects in real-time, with version control and change tracking.",
        "feature2": "Comment and feedback system",
        "feature2_desc": "Add comments and feedback directly to content, streamlining the review and revision process.",
        "feature3": "User permission management",
        "feature3_desc": "Set granular permissions to control who can view, edit, or publish your ebook projects.",
        "step1": "Create collaborative project",
        "step1_desc": "Set up a new ebook project and invite team members via email.",
        "step2": "Assign roles and permissions",
        "step2_desc": "Define each team member's role and access level within the project.",
        "step3": "Collaborate and review",
        "step3_desc": "Work together on content, leave comments, and track changes throughout the process.",
        "practice1": "Establish clear workflows",
        "practice1_desc": "Define roles and responsibilities upfront to ensure smooth collaboration.",
        "practice2": "Regularly review changes",
        "practice2_desc": "Schedule regular review sessions to ensure consistency and quality across the project.",
        "focus": "Collaborative ebook creation and team workflow"
    },
    7: {
        "feature1": "Built-in proofreading tools",
        "feature1_desc": "Catch grammar, spelling, and style issues with integrated proofreading and editing tools.",
        "feature2": "Readability analysis",
        "feature2_desc": "Analyze your content's readability score and receive suggestions for improvement.",
        "feature3": "Consistency checker",
        "feature3_desc": "Ensure consistent terminology and styling throughout your ebook.",
        "step1": "Write or import content",
        "step1_desc": "Create your ebook content or import existing material into the editor.",
        "step2": "Run proofreading tools",
        "step2_desc": "Use the built-in tools to identify and correct errors in grammar, spelling, and style.",
        "step3": "Review readability suggestions",
        "step3_desc": "Analyze readability scores and implement suggested improvements to enhance reader experience.",
        "practice1": "Read aloud for flow",
        "practice1_desc": "Read your content aloud to identify awkward phrasing and improve overall flow.",
        "practice2": "Get external feedback",
        "practice2_desc": "Have others review your ebook to catch errors and provide fresh perspectives.",
        "focus": "Content quality and proofreading for professional ebooks"
    },
    8: {
        "feature1": "Custom CSS styling",
        "feature1_desc": "Apply custom CSS styles to create unique formatting and design elements for your ebook.",
        "feature2": "Template library",
        "feature2_desc": "Access a library of pre-designed templates for different genres and styles.",
        "feature3": "Responsive design tools",
        "feature3_desc": "Ensure your ebook displays correctly across devices with different screen sizes.",
        "step1": "Select base template",
        "step1_desc": "Choose a template from the library that matches your ebook's genre and style.",
        "step2": "Customize with CSS",
        "step2_desc": "Modify the template's CSS to create your desired look and feel.",
        "step3": "Preview across devices",
        "step3_desc": "Test your styled ebook on different devices to ensure consistent display.",
        "practice1": "Keep styling consistent",
        "practice1_desc": "Maintain consistent styling throughout your ebook for a professional appearance.",
        "practice2": "Test on multiple devices",
        "practice2_desc": "Verify your custom styles display correctly on various e-readers and apps.",
        "focus": "Custom styling and template customization for ebooks"
    },
    9: {
        "feature1": "Audio integration",
        "feature1_desc": "Add audio elements to your ebook, creating an immersive multimedia experience.",
        "feature2": "Video embedding",
        "feature2_desc": "Embed video content that plays directly within supported ebook readers.",
        "feature3": "Interactive elements",
        "feature3_desc": "Add interactive quizzes, polls, and other elements to engage readers.",
        "step1": "Prepare multimedia content",
        "step1_desc": "Create or gather audio and video files you want to include in your ebook.",
        "step2": "Embed multimedia elements",
        "step2_desc": "Add audio and video files to your ebook content at appropriate points.",
        "step3": "Test multimedia functionality",
        "step3_desc": "Verify that audio and video elements play correctly on supported devices.",
        "practice1": "Optimize media files",
        "practice1_desc": "Compress audio and video files to minimize ebook size while maintaining quality.",
        "practice2": "Provide alternatives",
        "practice2_desc": "Include text alternatives for multimedia content to ensure accessibility.",
        "focus": "Multimedia integration and interactive ebook features"
    },
    10: {
        "feature1": "SEO optimization tools",
        "feature1_desc": "Optimize your ebook metadata and content for discoverability in online marketplaces.",
        "feature2": "Keyword research integration",
        "feature2_desc": "Research and incorporate relevant keywords to improve search visibility.",
        "feature3": "Metadata optimization",
        "feature3_desc": "Fine-tune title, description, and other metadata fields for maximum discoverability.",
        "step1": "Research target keywords",
        "step1_desc": "Use the built-in keyword research tools to identify relevant terms for your ebook topic.",
        "step2": "Optimize metadata",
        "step2_desc": "Incorporate target keywords into your ebook title, description, and other metadata fields.",
        "step3": "Optimize content",
        "step3_desc": "Strategically include keywords throughout your content while maintaining natural readability.",
        "practice1": "Focus on user intent",
        "practice1_desc": "Target keywords that align with what users are actually searching for related to your ebook topic.",
        "practice2": "Avoid keyword stuffing",
        "practice2_desc": "Use keywords naturally and sparingly to maintain readability and avoid search penalties.",
        "focus": "SEO optimization and discoverability for ebooks"
    },
    11: {
        "feature1": "Distribution platform integration",
        "feature1_desc": "Directly publish your ebook to major platforms like Amazon Kindle, Apple Books, and Kobo.",
        "feature2": "Royalty tracking",
        "feature2_desc": "Monitor sales and royalties across multiple distribution channels from a single dashboard.",
        "feature3": "Distribution analytics",
        "feature3_desc": "Track performance metrics like download counts, reader engagement, and conversion rates.",
        "step1": "Prepare ebook for distribution",
        "step1_desc": "Ensure your ebook meets the formatting requirements of your target platforms.",
        "step2": "Connect distribution accounts",
        "step2_desc": "Link your accounts for Amazon Kindle, Apple Books, and other platforms.",
        "step3": "Publish and track",
        "step3_desc": "Publish your ebook to selected platforms and monitor performance through the analytics dashboard.",
        "practice1": "Research platform requirements",
        "practice1_desc": "Familiarize yourself with the specific formatting and content guidelines for each platform.",
        "practice2": "Optimize for each platform",
        "practice2_desc": "Tailor your ebook's metadata and pricing for each distribution channel to maximize visibility.",
        "focus": "Ebook distribution and sales analytics"
    },
    12: {
        "feature1": "Accessibility compliance tools",
        "feature1_desc": "Ensure your ebook meets WCAG and other accessibility standards for readers with disabilities.",
        "feature2": "Screen reader compatibility",
        "feature2_desc": "Test and optimize your ebook for compatibility with screen readers and other assistive technologies.",
        "feature3": "Accessibility checklist",
        "feature3_desc": "Use the built-in checklist to ensure your ebook meets all accessibility requirements.",
        "step1": "Create accessible content",
        "step1_desc": "Write and format your content with accessibility in mind, using proper heading structure and descriptive alt text.",
        "step2": "Run accessibility checks",
        "step2_desc": "Use the built-in tools to identify and fix accessibility issues in your ebook.",
        "step3": "Test with assistive technologies",
        "step3_desc": "Verify your ebook works correctly with screen readers and other assistive devices.",
        "practice1": "Use meaningful headings",
        "practice1_desc": "Structure your content with clear, hierarchical headings to improve navigation for screen reader users.",
        "practice2": "Provide descriptive alt text",
        "practice2_desc": "Add detailed alt text to all images to ensure visually impaired readers can understand visual content.",
        "focus": "Ebook accessibility and compliance"
    },
    13: {
        "feature1": "Version control system",
        "feature1_desc": "Track changes to your ebook over time, with the ability to revert to previous versions if needed.",
        "feature2": "Backup and restore",
        "feature2_desc": "Automatically back up your ebook projects and restore them from any point in time.",
        "feature3": "Change history",
        "feature3_desc": "View a detailed history of all changes made to your ebook project.",
        "step1": "Create versioned project",
        "step1_desc": "Set up your ebook project with version control enabled.",
        "step2": "Work on content",
        "step2_desc": "Make changes to your ebook content, with all edits tracked automatically.",
        "step3": "Review and revert",
        "step3_desc": "Review change history and revert to previous versions if needed.",
        "practice1": "Regularly commit changes",
        "practice1_desc": "Make frequent commits with descriptive messages to maintain a clear change history.",
        "practice2": "Test before publishing",
        "practice2_desc": "Always test the final version of your ebook before publishing to ensure all changes work as expected.",
        "focus": "Version control and project management for ebooks"
    },
    14: {
        "feature1": "Monetization options",
        "feature1_desc": "Explore various monetization strategies including direct sales, subscriptions, and affiliate marketing.",
        "feature2": "Pricing strategy tools",
        "feature2_desc": "Analyze market trends and competitor pricing to set optimal prices for your ebook.",
        "feature3": "Promotional tools",
        "feature3_desc": "Create discount codes, limited-time offers, and other promotional campaigns to boost sales.",
        "step1": "Define monetization strategy",
        "step1_desc": "Choose the right monetization model for your ebook based on your target audience and content type.",
        "step2": "Set pricing",
        "step2_desc": "Use the pricing tools to set competitive prices that maximize revenue.",
        "step3": "Create promotions",
        "step3_desc": "Set up promotional campaigns to drive sales and attract new readers.",
        "practice1": "Research market rates",
        "practice1_desc": "Investigate what similar ebooks in your genre are selling for to set competitive prices.",
        "practice2": "Offer multiple formats",
        "practice2_desc": "Provide your ebook in multiple formats at different price points to cater to different reader preferences.",
        "focus": "Ebook monetization and pricing strategies"
    },
    15: {
        "feature1": "User feedback collection",
        "feature1_desc": "Gather reader feedback through built-in surveys and reviews to improve your ebook.",
        "feature2": "Reader analytics",
        "feature2_desc": "Track how readers interact with your ebook, including which sections they read most and how long they spend reading.",
        "feature3": "A/B testing",
        "feature3_desc": "Test different cover designs, titles, and descriptions to optimize reader engagement.",
        "step1": "Set up feedback mechanisms",
        "step1_desc": "Configure surveys and review prompts to collect reader feedback.",
        "step2": "Analyze reader data",
        "step2_desc": "Review analytics to understand how readers are engaging with your content.",
        "step3": "Implement improvements",
        "step3_desc": "Use feedback and analytics to make data-driven improvements to your ebook.",
        "practice1": "Act on feedback promptly",
        "practice1_desc": "Respond to reader feedback quickly and make necessary adjustments to improve your ebook.",
        "practice2": "Test changes incrementally",
        "practice2_desc": "Make small, targeted changes and measure their impact before implementing larger revisions.",
        "focus": "Reader feedback and engagement analytics"
    },
    16: {
        "feature1": "Integration with content management systems",
        "feature1_desc": "Connect with popular CMS platforms like WordPress and Drupal to streamline content workflow.",
        "feature2": "API access",
        "feature2_desc": "Use the free_ebook_maker API to automate ebook creation and management processes.",
        "feature3": "Third-party tool integration",
        "feature3_desc": "Integrate with tools like Grammarly, Canva, and Google Analytics for enhanced functionality.",
        "step1": "Connect external tools",
        "step1_desc": "Link your free_ebook_maker account with your existing CMS and other tools.",
        "step2": "Set up automation workflows",
        "step2_desc": "Create automated workflows to streamline your ebook creation process.",
        "step3": "Sync content",
        "step3_desc": "Keep your ebook content in sync with your CMS and other connected tools.",
        "practice1": "Document integration workflows",
        "practice1_desc": "Create clear documentation for your integration workflows to ensure consistency.",
        "practice2": "Test integrations regularly",
        "practice2_desc": "Periodically test your integrations to ensure they continue to work correctly as tools update.",
        "focus": "Ebook tool integrations and workflow automation"
    },
    17: {
        "feature1": "Advanced formatting options",
        "feature1_desc": "Access advanced formatting tools including drop caps, pull quotes, and custom page layouts.",
        "feature2": "Typography presets",
        "feature2_desc": "Choose from professional typography presets optimized for different genres and reading experiences.",
        "feature3": "Layout templates",
        "feature3_desc": "Select from a variety of pre-designed layout templates for different ebook types.",
        "step1": "Choose layout template",
        "step1_desc": "Select a layout template that matches your ebook's genre and content type.",
        "step2": "Apply typography settings",
        "step2_desc": "Choose a typography preset or customize font settings to create your desired look.",
        "step3": "Add advanced formatting",
        "step3_desc": "Enhance your ebook with drop caps, pull quotes, and other advanced formatting elements.",
        "practice1": "Maintain consistency",
        "practice1_desc": "Apply formatting consistently throughout your ebook for a professional appearance.",
        "practice2": "Test on different devices",
        "practice2_desc": "Verify that advanced formatting elements display correctly across different e-reader devices.",
        "focus": "Advanced formatting and typography for professional ebooks"
    },
    18: {
        "feature1": "Cloud storage integration",
        "feature1_desc": "Save and access your ebook projects from cloud storage services like Dropbox, Google Drive, and OneDrive.",
        "feature2": "Offline editing",
        "feature2_desc": "Work on your ebook projects offline and sync changes when you reconnect to the internet.",
        "feature3": "Cross-device synchronization",
        "feature3_desc": "Seamlessly switch between devices while working on your ebook project.",
        "step1": "Connect cloud storage",
        "step1_desc": "Link your cloud storage accounts to free_ebook_maker for automatic syncing.",
        "step2": "Work on projects",
        "step2_desc": "Edit your ebook projects on any device, with changes saved to the cloud.",
        "step3": "Access from anywhere",
        "step3_desc": "Open and continue working on your projects from any device with internet access.",
        "practice1": "Regularly back up",
        "practice1_desc": "Even with cloud syncing, maintain regular backups of your ebook projects.",
        "practice2": "Organize files effectively",
        "practice2_desc": "Use clear naming conventions and folder structures to keep your ebook projects organized.",
        "focus": "Cloud storage and cross-device workflow for ebooks"
    },
    19: {
        "feature1": "Language translation tools",
        "feature1_desc": "Translate your ebook into multiple languages to reach a global audience.",
        "feature2": "Localization support",
        "feature2_desc": "Adapt your ebook content for different regional markets and cultural contexts.",
        "feature3": "Multilingual metadata",
        "feature3_desc": "Create localized metadata for each language version of your ebook.",
        "step1": "Prepare content for translation",
        "step1_desc": "Structure your content in a way that makes translation easier and more accurate.",
        "step2": "Translate content",
        "step2_desc": "Use the built-in translation tools or connect with professional translators to translate your ebook.",
        "step3": "Localize and publish",
        "step3_desc": "Adapt content for local markets and publish multilingual versions of your ebook.",
        "practice1": "Work with native speakers",
        "practice1_desc": "Have native speakers review translations to ensure accuracy and cultural appropriateness.",
        "practice2": "Consider regional preferences",
        "practice2_desc": "Adapt examples, references, and cultural context to resonate with local readers.",
        "focus": "Ebook translation and localization for global markets"
    },
    20: {
        "feature1": "Ebook marketing tools",
        "feature1_desc": "Access built-in tools for creating marketing materials like landing pages, social media posts, and email campaigns.",
        "feature2": "Audience targeting",
        "feature2_desc": "Identify and target specific reader demographics to maximize marketing effectiveness.",
        "feature3": "Campaign tracking",
        "feature3_desc": "Monitor the performance of your ebook marketing campaigns with detailed analytics.",
        "step1": "Create marketing assets",
        "step1_desc": "Use the built-in tools to create landing pages, social media graphics, and other marketing materials.",
        "step2": "Launch campaigns",
        "step2_desc": "Set up and launch targeted marketing campaigns for your ebook.",
        "step3": "Track results",
        "step3_desc": "Monitor campaign performance and adjust strategies based on analytics data.",
        "practice1": "Define target audience",
        "practice1_desc": "Clearly identify your target reader demographic to create more effective marketing campaigns.",
        "practice2": "Test different approaches",
        "practice2_desc": "Experiment with different marketing strategies to find what works best for your ebook.",
        "focus": "Ebook marketing and audience targeting"
    },
    21: {
        "feature1": "Print-on-demand integration",
        "feature1_desc": "Create print-ready versions of your ebook for print-on-demand services.",
        "feature2": "Interior layout tools",
        "feature2_desc": "Design professional interior layouts optimized for print formats.",
        "feature3": "Cover design for print",
        "feature3_desc": "Create print-ready cover designs that meet the requirements of print-on-demand services.",
        "step1": "Prepare print version",
        "step1_desc": "Adjust your ebook content and layout for print format.",
        "step2": "Design print cover",
        "step2_desc": "Create a print-ready cover design that meets the specifications of your chosen print service.",
        "step3": "Publish to print-on-demand",
        "step3_desc": "Submit your print-ready files to print-on-demand services for physical distribution.",
        "practice1": "Follow print specifications",
        "practice1_desc": "Strictly adhere to the formatting and size requirements of your chosen print-on-demand service.",
        "practice2": "Proof physical copies",
        "practice2_desc": "Order proof copies of your printed book to check for any formatting or design issues.",
        "focus": "Print-on-demand integration for ebooks"
    },
    22: {
        "feature1": "Collaborative brainstorming tools",
        "feature1_desc": "Use built-in brainstorming tools to generate ideas and outline your ebook content.",
        "feature2": "Mind mapping",
        "feature2_desc": "Create visual mind maps to organize your ebook's structure and content flow.",
        "feature3": "Content planning calendar",
        "feature3_desc": "Use the built-in calendar to plan and schedule your ebook creation process.",
        "step1": "Brainstorm ideas",
        "step1_desc": "Use the brainstorming tools to generate and organize ideas for your ebook.",
        "step2": "Create content outline",
        "step2_desc": "Develop a detailed outline for your ebook using the mind mapping tools.",
        "step3": "Set创作 schedule",
        "step3_desc": "Use the content calendar to plan your writing and production timeline.",
        "practice1": "Start with a clear outline",
        "practice1_desc": "Create a comprehensive outline before beginning to write to maintain focus and structure.",
        "practice2": "Break down large tasks",
        "practice2_desc": "Divide your ebook creation process into smaller, manageable tasks to avoid overwhelm.",
        "focus": "Ebook planning and content organization"
    },
    23: {
        "feature1": "Advanced search functionality",
        "feature1_desc": "Implement powerful search capabilities within your ebook to help readers find content quickly.",
        "feature2": "Indexing tools",
        "feature2_desc": "Create comprehensive indexes for non-fiction ebooks to improve navigation.",
        "feature3": "Cross-referencing",
        "feature3_desc": "Add internal cross-references to related content within your ebook.",
        "step1": "Enable search functionality",
        "step1_desc": "Activate and configure the search capabilities for your ebook.",
        "step2": "Create index",
        "step2_desc": "Generate an index for your ebook, including important terms and concepts.",
        "step3": "Add cross-references",
        "step3_desc": "Insert cross-references to related content throughout your ebook.",
        "practice1": "Use consistent terminology",
        "practice1_desc": "Maintain consistent terminology throughout your ebook to improve search results.",
        "practice2": "Test search functionality",
        "practice2_desc": "Verify that search works correctly and returns relevant results for key terms.",
        "focus": "Ebook search functionality and indexing"
    },
    24: {
        "feature1": "Social media integration",
        "feature1_desc": "Add social sharing buttons and integration with platforms like Facebook, Twitter, and LinkedIn.",
        "feature2": "Reader commenting",
        "feature2_desc": "Allow readers to leave comments and discussions within your ebook.",
        "feature3": "Community building tools",
        "feature3_desc": "Create reader communities around your ebook content with built-in discussion forums.",
        "step1": "Enable social features",
        "step1_desc": "Activate social media integration and commenting features for your ebook.",
        "step2": "Customize sharing options",
        "step2_desc": "Configure which social platforms readers can share content to.",
        "step3": "Moderate discussions",
        "step3_desc": "Set up moderation tools to manage reader comments and discussions.",
        "practice1": "Encourage engagement",
        "practice1_desc": "Include prompts throughout your ebook to encourage readers to share content and leave comments.",
        "practice2": "Respond to comments",
        "practice2_desc": "Regularly engage with reader comments to build community and improve your ebook.",
        "focus": "Social media integration and reader community building"
    },
    25: {
        "feature1": "Ebook security features",
        "feature1_desc": "Protect your ebook content with DRM (Digital Rights Management) and watermarking.",
        "feature2": "Piracy prevention",
        "feature2_desc": "Implement anti-piracy measures to protect your intellectual property.",
        "feature3": "Access control",
        "feature3_desc": "Set permissions and access controls for different reader groups.",
        "step1": "Choose security options",
        "step1_desc": "Select the appropriate security measures for your ebook based on your content and distribution strategy.",
        "step2": "Configure DRM settings",
        "step2_desc": "Set up DRM protection and watermarking for your ebook.",
        "step3": "Test security measures",
        "step3_desc": "Verify that your security measures work correctly while maintaining a good reader experience.",
        "practice1": "Balance security and usability",
        "practice1_desc": "Implement security measures that protect your content without significantly impacting the reader experience.",
        "practice2": "Stay updated on piracy trends",
        "practice2_desc": "Keep informed about the latest piracy techniques and update your security measures accordingly.",
        "focus": "Ebook security and piracy prevention"
    },
    26: {
        "feature1": "Interactive learning tools",
        "feature1_desc": "Create interactive quizzes, exercises, and assessments for educational ebooks.",
        "feature2": "Progress tracking",
        "feature2_desc": "Allow readers to track their progress through educational content and assessments.",
        "feature3": "Certification support",
        "feature3_desc": "Generate certificates of completion for educational ebooks and courses.",
        "step1": "Design interactive elements",
        "step1_desc": "Create quizzes, exercises, and other interactive elements for your educational ebook.",
        "step2": "Set up progress tracking",
        "step2_desc": "Configure the progress tracking system to monitor reader completion.",
        "step3": "Implement certification",
        "step3_desc": "Set up certificate generation for readers who complete your educational content.",
        "practice1": "Align with learning objectives",
        "practice1_desc": "Ensure interactive elements directly support your educational objectives.",
        "practice2": "Provide immediate feedback",
        "practice2_desc": "Offer clear feedback on quiz answers to enhance the learning experience.",
        "focus": "Interactive learning features for educational ebooks"
    },
    27: {
        "feature1": "Data visualization tools",
        "feature1_desc": "Create interactive charts, graphs, and data visualizations for data-driven ebooks.",
        "feature2": "Live data integration",
        "feature2_desc": "Connect to live data sources to keep information up-to-date in your ebook.",
        "feature3": "Custom visualization templates",
        "feature3_desc": "Use pre-designed templates to create professional data visualizations quickly.",
        "step1": "Import or connect to data",
        "step1_desc": "Import static data or connect to live data sources for your visualizations.",
        "step2": "Create visualizations",
        "step2_desc": "Use the visualization tools to create charts, graphs, and other data displays.",
        "step3": "Integrate into ebook",
        "step3_desc": "Embed the visualizations into your ebook content at appropriate points.",
        "practice1": "Simplify complex data",
        "practice1_desc": "Present complex data in clear, easy-to-understand visualizations.",
        "practice2": "Test interactivity",
        "practice2_desc": "Verify that interactive visualizations work correctly across different devices.",
        "focus": "Data visualization and interactive data displays in ebooks"
    },
    28: {
        "feature1": "Audio narration support",
        "feature1_desc": "Add professional audio narration to your ebook for audiobook versions.",
        "feature2": "Text-to-speech integration",
        "feature2_desc": "Convert your ebook text to speech with natural-sounding voices.",
        "feature3": "Audio synchronization",
        "feature3_desc": "Sync audio narration with text highlighting for an enhanced reading experience.",
        "step1": "Prepare audio content",
        "step1_desc": "Record professional narration or use text-to-speech to generate audio versions of your content.",
        "step2": "Sync audio with text",
        "step2_desc": "Align audio narration with the corresponding text in your ebook.",
        "step3": "Test audio functionality",
        "step3_desc": "Verify that audio plays correctly and synchronizes properly with text.",
        "practice1": "Use professional narration",
        "practice1_desc": "Invest in professional narration for a higher-quality audiobook experience.",
        "practice2": "Optimize audio quality",
        "practice2_desc": "Ensure audio files are properly compressed and formatted for ebook distribution.",
        "focus": "Audio narration and audiobook features"
    },
    29: {
        "feature1": "Gamification elements",
        "feature1_desc": "Add game-like elements such as achievements, badges, and progress bars to increase reader engagement.",
        "feature2": "Interactive storytelling",
        "feature2_desc": "Create choose-your-own-adventure style stories with branching narratives.",
        "feature3": "Reader challenges",
        "feature3_desc": "Set up challenges and rewards to motivate readers to complete your ebook.",
        "step1": "Design gamification elements",
        "step1_desc": "Create badges, achievements, and other gamification elements for your ebook.",
        "step2": "Implement interactive elements",
        "step2_desc": "Add branching narratives and interactive elements to your content.",
        "step3": "Set up reward system",
        "step3_desc": "Configure the reward system to recognize reader achievements.",
        "practice1": "Balance gamification with content",
        "practice1_desc": "Ensure gamification elements enhance rather than distract from your core content.",
        "practice2": "Test engagement metrics",
        "practice2_desc": "Monitor how gamification elements affect reader engagement and completion rates.",
        "focus": "Gamification and interactive storytelling in ebooks"
    },
    30: {
        "feature1": "AI-powered content generation",
        "feature1_desc": "Use AI to generate content ideas, outlines, and even complete sections for your ebook.",
        "feature2": "Smart editing suggestions",
        "feature2_desc": "Receive AI-powered suggestions for improving your writing style, clarity, and structure.",
        "feature3": "Content optimization",
        "feature3_desc": "Use AI to optimize your content for readability, engagement, and SEO.",
        "step1": "Generate content ideas",
        "step1_desc": "Use the AI tools to generate ideas and outlines for your ebook content.",
        "step2": "Write and edit content",
        "step2_desc": "Create content with the help of AI suggestions and editing tools.",
        "step3": "Optimize final content",
        "step3_desc": "Use AI to analyze and optimize your completed ebook for maximum impact.",
        "practice1": "Use AI as a tool, not a replacement",
        "practice1_desc": "Leverage AI to enhance your writing process, but maintain your unique voice and perspective.",
        "practice2": "Review AI-generated content",
        "practice2_desc": "Always review and edit AI-generated content to ensure accuracy and consistency with your brand.",
        "focus": "AI-powered content creation and optimization for ebooks"
    }
}

# 主目录路径
BASE_DIR = "E:\\Developer-Toolbox-by-WangDadi\\free_ebook_maker\\manual"

def generate_content():
    print("开始为 free_ebook_maker 生成真实内容...")
    
    # 处理英文文件
    for i in range(1, 31):
        file_name = f"FRE_{i:03d}.md"
        file_path = os.path.join(BASE_DIR, file_name)
        
        if os.path.exists(file_path):
            # 读取文件内容
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 获取对应模板
            template = content_templates.get(i, content_templates[1])
            
            # 替换内容
            content = content.replace("Describe feature 1", f"{template['feature1']}: {template['feature1_desc']}")
            content = content.replace("Describe feature 2", f"{template['feature2']}: {template['feature2_desc']}")
            content = content.replace("Describe feature 3", f"{template['feature3']}: {template['feature3_desc']}")
            
            content = content.replace("Describe Step 1", f"{template['step1']}: {template['step1_desc']}")
            content = content.replace("Describe Step 2", f"{template['step2']}: {template['step2_desc']}")
            content = content.replace("Describe Step 3", f"{template['step3']}: {template['step3_desc']}")
            
            content = content.replace("Describe Practice 1", f"{template['practice1']}: {template['practice1_desc']}")
            content = content.replace("Describe Practice 2", f"{template['practice2']}: {template['practice2_desc']}")
            
            # 更新 SEO 内容
            seo_pattern = r"This is SEO optimized content for the free_ebook_maker project, keywords:.*"
            new_seo = f"This is SEO optimized content for the free_ebook_maker project, keywords: {template['focus']}, {template['feature1']}, {template['feature2']}, {template['feature3']}"
            import re
            content = re.sub(seo_pattern, new_seo, content)
            
            # 写回文件
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"已更新 {file_path}")
    
    print("英文内容生成完成！")

if __name__ == "__main__":
    generate_content()
